name: Civilization
version: "2.1"
api-version: 1.16
api: "1.16"
main: me.boykev.kingdom.Main
author: boykev
depend: [KingdomCraft,KingdomCraftPremium]
commands:
  civilization:
    description: Main base command.
  civspawn:
    description: Main base command.
  civcheck:
    description: Main base command.
  civadmin:
    description: Main base command.
  civinvite:
    description: Main base command.
  kd-invitemanager:
    description: Main base command.
  rulemanager-accept:
    description: Main base command.
  civ-create:
    description: Main base command.