name: Fire-Kingdom2
version: 3.0
main: me.boykev.kingdom.Main
author: boykev
depend: [KingdomCraft,KingdomCraftPremium]
commands:
  kd-selector:
    description: Kingdom Selector Commando.
  fire-kingdom:
    description: Main base command.
  kdsetspawn:
    description: Main base command.
  kdspawn:
    description: Main base command.
  setkingdom:
    description: Main base command.
  check-kingdom:
    description: Main base command.
  kd-admin:
    description: Main base command.
  kd-invite:
    description: Main base command.
  kd-invitemanager:
    description: Main base command.
  godhp:
    description: Main base command.
  steal:
    description: Main base command.
  rulemanager-accept:
    description: Main base command.
  kdsetcolor:
    description: Main base command.