name: Civilization
version: "2.1"
api-version: 1.16
api: "1.16"
main: me.boykev.kingdom.Main
author: boykev
depend: [KingdomCraft]
commands:
  civilization:
    description: Main base command.
  civspawn:
    description: Main base command.
  civcheck:
    description: Main base command.
  civadmin:
    description: Main base command.
  civinvite:
    description: Main base command.
  kd-invitemanager:
    description: Main base command.
  rulemanager-accept:
    description: Main base command.
  civ-create:
    description: Main base command.
  civsetspawn:
    description: Main base command.
  discord:
    description: Main base command.
  civsethome:
    description: Main base command.
  civhome:
    description: Main base command.
  repair:
    description: Main base command.
  repaira:
    description: Main base command.
  repairb:
    description: Main base command.
  repairc:
    description: Main base command.
  cpitem:
    description: Main base command.
  setpower:
    description: Main base command.
  removebox:
    description: Main base command.
  online:
    description: Main base command.
  borders:
    description: Main base command.
  poef:
    description: Main base command.
  poef2:
    description: Main base command.
  goatclear:
    description: Main base command.